//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cfdg.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICfdgListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class CfdgBaseListener : ICfdgListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.contextfree"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContextfree([NotNull] CfdgParser.ContextfreeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.contextfree"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContextfree([NotNull] CfdgParser.ContextfreeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] CfdgParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] CfdgParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CfdgParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CfdgParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.startshape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartshape([NotNull] CfdgParser.StartshapeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.startshape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartshape([NotNull] CfdgParser.StartshapeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.background"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBackground([NotNull] CfdgParser.BackgroundContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.background"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBackground([NotNull] CfdgParser.BackgroundContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.design_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesign_rule([NotNull] CfdgParser.Design_ruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.design_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesign_rule([NotNull] CfdgParser.Design_ruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplacements([NotNull] CfdgParser.ReplacementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.replacements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplacements([NotNull] CfdgParser.ReplacementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.replacement_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplacement_loop([NotNull] CfdgParser.Replacement_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.replacement_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplacement_loop([NotNull] CfdgParser.Replacement_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.replacement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReplacement([NotNull] CfdgParser.ReplacementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.replacement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReplacement([NotNull] CfdgParser.ReplacementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.modification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModification([NotNull] CfdgParser.ModificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.modification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModification([NotNull] CfdgParser.ModificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.adjustments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdjustments([NotNull] CfdgParser.AdjustmentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.adjustments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdjustments([NotNull] CfdgParser.AdjustmentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.adjustment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdjustment([NotNull] CfdgParser.AdjustmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.adjustment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdjustment([NotNull] CfdgParser.AdjustmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.color_adjustments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor_adjustments([NotNull] CfdgParser.Color_adjustmentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.color_adjustments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor_adjustments([NotNull] CfdgParser.Color_adjustmentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.geom_adjustment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeom_adjustment([NotNull] CfdgParser.Geom_adjustmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.geom_adjustment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeom_adjustment([NotNull] CfdgParser.Geom_adjustmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.color_adjustment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor_adjustment([NotNull] CfdgParser.Color_adjustmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.color_adjustment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor_adjustment([NotNull] CfdgParser.Color_adjustmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CfdgParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum([NotNull] CfdgParser.NumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CfdgParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum([NotNull] CfdgParser.NumContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
