//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cfdg.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CfdgParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface ICfdgVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.contextfree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContextfree([NotNull] CfdgParser.ContextfreeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] CfdgParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CfdgParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.startshape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartshape([NotNull] CfdgParser.StartshapeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.background"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBackground([NotNull] CfdgParser.BackgroundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.design_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesign_rule([NotNull] CfdgParser.Design_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.replacements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplacements([NotNull] CfdgParser.ReplacementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.replacement_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplacement_loop([NotNull] CfdgParser.Replacement_loopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.replacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReplacement([NotNull] CfdgParser.ReplacementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.modification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModification([NotNull] CfdgParser.ModificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.adjustments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdjustments([NotNull] CfdgParser.AdjustmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.adjustment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdjustment([NotNull] CfdgParser.AdjustmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.color_adjustments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColor_adjustments([NotNull] CfdgParser.Color_adjustmentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.geom_adjustment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeom_adjustment([NotNull] CfdgParser.Geom_adjustmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.color_adjustment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColor_adjustment([NotNull] CfdgParser.Color_adjustmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CfdgParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum([NotNull] CfdgParser.NumContext context);
}
